---
title: "Initial Analysis"
output: html_document
date: "2025-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
```


#The first thing we want to do before we analyze all of the data is to check and isolate the patients which have all three datasets which is clinical data, mutation data, and expression data. 

```{r}

#First we will read all three data sets 
  
clinical_data <- read.delim("data_clinical_patient.txt", header = TRUE, stringsAsFactors = FALSE)
mutation_data <- read.delim("data_mutations.txt", header = TRUE, stringsAsFactors = FALSE)
rnaseq_data <- read.csv("RNAseq_LIHC.csv", stringsAsFactors = FALSE)
```


```{r}
extract_id <- function(tcga_codes) {
  tcga_codes <- as.character(tcga_codes)

  ids <- sub("^TCGA-[A-Z0-9]{2}-([A-Z0-9]{4}).*", "\\1", tcga_codes)
  
  return(ids)
}
```


```{r}
extract_id_rnaseq <- function(tcga_codes) {
  tcga_codes <- as.character(tcga_codes)

  ids <- sub("^TCGA.[A-Z0-9]{2}.([A-Z0-9]{4}).*", "\\1", tcga_codes)
  
  return(ids)
}
```


```{r}
clinical_data_patients_id <- extract_id(tcga_codes = clinical_data$X.Patient.Identifier)
clinical_data_patients_id <- clinical_data_patients_id[-(1:4)]

mutational_data_patients_id <- unique(extract_id(tcga_codes = mutation_data$Tumor_Sample_Barcode))

rnaseq_data_cleaned <- rnaseq_data[,-1 ]

rnaseq_data_patients_id <- unique(extract_id_rnaseq(tcga_codes = colnames(rnaseq_data)))

common_patients_id <- clinical_data_patients_id[clinical_data_patients_id %in% mutational_data_patients_id &
clinical_data_patients_id %in% rnaseq_data_patients_id ]
```


```{r}
clinical_full_data <- clinical_data[ which(clinical_data_patients_id  %in% common_patients_id),  ]

mutational_full_data <- mutation_data[which(mutational_data_patients_id  %in% common_patients_id), ] 

clinical_full_data <- clinical_data[-c(1:4), ]

colnames(clinical_full_data)
```


```{r}
key_vars <- c(
  "Diagnosis.Age",
  "Sex",
  "Ethnicity.Category",
  "Overall.Survival.Status",
  "Overall.Survival..Months.", 
  "Disease.specific.Survival.status",                                                           
  "Months.of.disease.specific.survival" 
)

clinical_clean <- clinical_full_data %>%
  filter(!is.na(X.Patient.Identifier) & X.Patient.Identifier != "") %>%
  filter(complete.cases(across(all_of(key_vars))))
```



```{r}

#Age Distribution
clinical_full_data$Diagnosis.Age <- as.numeric(clinical_full_data$Diagnosis.Age)

ggplot(clinical_full_data, aes(x = Diagnosis.Age)) +
geom_histogram(bins =50, fill = "steelblue", color = "black") +
labs(title = "Age Distribution of Patients",
x = "Age (years)",
y = "Count") +
theme_minimal()

print( median(clinical_full_data$Diagnosis.Age, na.rm = TRUE) )

```
```{r}
extract_survival_code <- function(status_strings) {
  status_strings <- as.character(status_strings)
  

  codes <- sub("^([01]).*", "\\1", status_strings)
  
  return(codes)
}
```


```{r}
clinical_full_data$Survival.Status.disease <-  extract_survival_code(clinical_full_data$Disease.specific.Survival.status)

clinical_full_data$Survival.Status.disease
```

```{r}
ggplot(clinical_full_data, aes(x = Survival.Status.disease, y = Diagnosis.Age)) +
  geom_violin(fill = "skyblue", alpha = 0.6, trim = FALSE) +
  geom_boxplot(width = 0.15, fill = "white", outlier.shape = NA) +
  labs(
    title = "Age at Diagnosis by Survival Status (Violin Plot)",
    x = "Survival Status",
    y = "Age at Diagnosis"
  ) +
  theme_minimal()
```


```{r}
ggplot(clinical_full_data, aes(x = Sex)) +
  geom_bar(color = "black", fill = "steelblue") +
  labs(
    title = "Number of Diagnoses by Sex",
    x = "Sex",
    y = "Number of Diagnosed Patients"
  ) +
  theme_minimal()
```



```{r}
ggplot(clinical_full_data, aes(x = Sex, fill = Survival.Status.disease)) +
  geom_bar(position = "dodge", color = "black") +
  labs(
    title = "Sex vs Survival Status",
    x = "Sex",
    y = "Patient Count",
    fill = "Survival Status"
  ) +
  theme_minimal()


death_stats <- clinical_full_data %>%
  group_by(Sex) %>%
  summarise(
    number_died = sum(Survival.Status.disease == 1, na.rm = TRUE),
    total = n(),
    percent_died = round(100 * number_died / total, 2),
    .groups = "drop"
  )

death_stats
```
```{r}

 
```

